[package]
name = "modbus-iskra-srvr"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = "4.5.16"
net2 = "0.2.39"
nix = "0.29.0"
once_cell = "1.19.0"
rmodbus = "0.9.9"
serde = { version = "1.0.214", features = ["derive"] }
serde_yaml = "0.9.34"
serial = "0.4.0"
